# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.4 87bd895"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "swap-lock-script"
template_type = "Rust"

[[contracts]]
name = "liquidity-lock-script"
template_type = "Rust"

[[contracts]]
name = "info-lock-script"
template_type = "Rust"

[[contracts]]
name = "info-type-script"
template_type = "Rust"
